import type { Stats, TypeChart } from './types.js';

export const NATURE_MAP: Record<string, [keyof Stats, keyof Stats]> = {
	Adamant: ['atk', 'spa'],
	Bashful: ['spa', 'spa'],
	Bold: ['def', 'atk'],
	Brave: ['atk', 'spe'],
	Calm: ['spd', 'atk'],
	Careful: ['spd', 'spa'],
	Docile: ['def', 'def'],
	Gentle: ['spd', 'def'],
	Hardy: ['atk', 'atk'],
	Hasty: ['spe', 'def'],
	Impish: ['def', 'spa'],
	Jolly: ['spe', 'spa'],
	Lax: ['def', 'spd'],
	Lonely: ['atk', 'def'],
	Mild: ['spa', 'def'],
	Modest: ['spa', 'atk'],
	Naive: ['spe', 'spd'],
	Naughty: ['atk', 'spd'],
	Quiet: ['spa', 'spe'],
	Quirky: ['spd', 'spd'],
	Rash: ['spa', 'spd'],
	Relaxed: ['def', 'spe'],
	Sassy: ['spd', 'spe'],
	Serious: ['spe', 'spe'],
	Timid: ['spe', 'atk'],
};

export const TYPE_CHART: TypeChart = {
	Normal: { immunes: ['Ghost'], weaknesses: ['Rock', 'Steel'], strengths: [] },
	Fire: { immunes: [], weaknesses: ['Fire', 'Water', 'Rock', 'Dragon'], strengths: ['Grass', 'Ice', 'Bug', 'Steel'] },
	Water: { immunes: [], weaknesses: ['Water', 'Grass', 'Dragon'], strengths: ['Fire', 'Ground', 'Rock'] },
	Electric: { immunes: ['Ground'], weaknesses: ['Electric', 'Grass', 'Dragon'], strengths: ['Water', 'Flying'] },
	Grass: { immunes: [], weaknesses: ['Fire', 'Grass', 'Poison', 'Flying', 'Bug', 'Dragon', 'Steel'], strengths: ['Water', 'Ground', 'Rock'] },
	Ice: { immunes: [], weaknesses: ['Fire', 'Water', 'Ice', 'Steel'], strengths: ['Grass', 'Ground', 'Flying', 'Dragon'] },
	Fighting: { immunes: ['Ghost'], weaknesses: ['Poison', 'Flying', 'Psychic', 'Bug', 'Fairy'], strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'] },
	Poison: { immunes: ['Steel'], weaknesses: ['Poison', 'Ground', 'Rock', 'Ghost'], strengths: ['Grass', 'Fairy'] },
	Ground: { immunes: ['Flying'], weaknesses: ['Grass', 'Bug'], strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'] },
	Flying: { immunes: [], weaknesses: ['Electric', 'Rock', 'Steel'], strengths: ['Grass', 'Fighting', 'Bug'] },
	Psychic: { immunes: ['Dark'], weaknesses: ['Psychic', 'Steel'], strengths: ['Fighting', 'Poison'] },
	Bug: { immunes: [], weaknesses: ['Fire', 'Fighting', 'Poison', 'Flying', 'Ghost', 'Steel', 'Fairy'], strengths: ['Grass', 'Psychic', 'Dark'] },
	Rock: { immunes: [], weaknesses: ['Fighting', 'Ground', 'Steel'], strengths: ['Fire', 'Ice', 'Flying', 'Bug'] },
	Ghost: { immunes: ['Normal'], weaknesses: ['Dark'], strengths: ['Psychic', 'Ghost'] },
	Dragon: { immunes: ['Fairy'], weaknesses: ['Steel'], strengths: ['Dragon'] },
	Dark: { immunes: [], weaknesses: ['Fighting', 'Dark', 'Fairy'], strengths: ['Psychic', 'Ghost'] },
	Steel: { immunes: [], weaknesses: ['Fire', 'Water', 'Electric', 'Steel'], strengths: ['Ice', 'Rock', 'Fairy'] },
	Fairy: { immunes: [], weaknesses: ['Fire', 'Poison', 'Steel'], strengths: ['Fighting', 'Dragon', 'Dark'] },
};
